# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [1]:
print("Hello World!")

Hello World!

In [1]:
import pandas as pd
df = pd.read_csv("all_articles - FINAL DATASET.csv")
df.head()

,url,Country,Political Bias,source,date (dd/mm/yyyy),headline,snippet,description,keywords,positive/neutral/negative,comments (on pos/neutral/neg),open coding/categories,comments (on topics)
0,https://www.wsj.com/world/americas/canadas-car...,US,Center,WSJ,27/11/2025,Canada’s Carney Loses Cabinet Minister Over Ea...,The prime minister faces his first major polit...,NaN,NaN,Neutral,NaN,Canadian Domestic Governance/Economy/Industry,NaN
1,https://www.wsj.com/world/americas/canadas-car...,US,Center,WSJ,24/11/2025,Canada’s Carney Pondering Trip to Washington W...,A Carney spokeswoman said the prime minister c...,NaN,NaN,Neutral,NaN,Canada/US Relations,NaN
2,https://www.wsj.com/world/canadian-pm-carney-s...,US,Center,WSJ,01/11/2025,Canadian PM Carney Says He Apologized to Trump...,Canada’s prime minister said he made the apolo...,NaN,NaN,Neutral,NaN,Canada/US Relations,NaN
3,https://www.wsj.com/world/china/canada-pm-mark...,US,Center,WSJ,30/10/2025,The Canada-U.S. Trade War Is Pushing Carney Cl...,Canadian Prime Minister Mark Carney is expecte...,NaN,NaN,Neutral,NaN,Canada/US Relations,NaN
4,https://www.wsj.com/economy/canada-to-take-bol...,US,Center,WSJ,22/10/2025,"Canada to Take ‘Bold’ Risks to Reset Economy, ...",Prime Minister Mark Carney said one of the bud...,NaN,NaN,Neutral,NaN,Canada/US Relations,NaN

In [2]:
df["positive/neutral/negative"] = df["positive/neutral/negative"].str.lower().str.strip()

In [4]:

summary = (
    df.groupby(["Country", "positive/neutral/negative"])
      .size()
      .reset_index(name="count")
)


total = df.groupby("Country").size().reset_index(name="total")


summary = summary.merge(total, on="Country")


summary["percent"] = (summary["count"] / summary["total"] * 100).round(2)

summary

  Country positive/neutral/negative  count  total  percent
0  Canada                  negative     70    300    23.33
1  Canada                   neutral    202    300    67.33
2  Canada                  positive     28    300     9.33
3      US                  negative     23    200    11.50
4      US                   neutral    165    200    82.50
5      US                  positive     12    200     6.00

In [5]:
summary = (
    df.groupby(["Political Bias", "positive/neutral/negative"])
      .size()
      .reset_index(name="count")
)


total = df.groupby("Political Bias").size().reset_index(name="total")


summary = summary.merge(total, on="Political Bias")


summary["percent"] = (summary["count"] / summary["total"] * 100).round(2)

summary

  Political Bias positive/neutral/negative  count  total  percent
0         Center                  negative     19    209     9.09
1         Center                   neutral    175    209    83.73
2         Center                  positive     15    209     7.18
3           Left                  negative     11    146     7.53
4           Left                   neutral    116    146    79.45
5           Left                  positive     19    146    13.01
6          Right                  negative     63    144    43.75
7          Right                   neutral     75    144    52.08
8          Right                  positive      6    144     4.17
9         Right                    neutral      1      1   100.00

In [6]:
summary = (
    df.groupby(["source", "positive/neutral/negative"])
      .size()
      .reset_index(name="count")
)


total = df.groupby("source").size().reset_index(name="total")


summary = summary.merge(total, on="source")


summary["percent"] = (summary["count"] / summary["total"] * 100).round(2)

summary

                source positive/neutral/negative  count  total  percent
0   The New York Times                  negative      2     35     5.71
1   The New York Times                   neutral     29     35    82.86
2   The New York Times                  positive      4     35    11.43
3                  WSJ                  negative      3     35     8.57
4                  WSJ                   neutral     29     35    82.86
5                  WSJ                  positive      3     35     8.57
6           apnews.com                  negative      1     35     2.86
7           apnews.com                   neutral     33     35    94.29
8           apnews.com                  positive      1     35     2.86
9               cbc.ca                  negative      8     76    10.53
10              cbc.ca                   neutral     54     76    71.05
11              cbc.ca                  positive     14     76    18.42
12          ctvnews.ca                  negative     11     75    14.67
13          ctvnews.ca                   neutral     61     75    81.33
14          ctvnews.ca                  positive      3     75     4.00
15         foxnews.com                  negative      7     37    18.92
16         foxnews.com                   neutral     27     37    72.97
17         foxnews.com                  positive      3     37     8.11
18       globalnews.ca                  negative      5     74     6.76
19       globalnews.ca                   neutral     61     74    82.43
20       globalnews.ca                  positive      8     74    10.81
21    nationalpost.com                  negative     46     75    61.33
22    nationalpost.com                   neutral     26     75    34.67
23    nationalpost.com                  positive      3     75     4.00
24          nypost.com                  negative     10     33    30.30
25          nypost.com                   neutral     23     33    69.70
26             upi.com                   neutral     24     25    96.00
27             upi.com                  positive      1     25     4.00

In [10]:
sentiment_col = "positive/neutral/negative"
country_col = "Country"
bias_col = "Political Bias"   #changed the columns based on different analysis


df[sentiment_col] = df[sentiment_col].str.lower().str.strip()
df[bias_col] = df[bias_col].str.strip()


summary = (
    df.groupby([country_col, bias_col, sentiment_col])
      .size()
      .reset_index(name="count")
)


totals = (
    df.groupby([country_col, bias_col])
      .size()
      .reset_index(name="total")
)


summary = summary.merge(totals, on=[country_col, bias_col])


summary["percent"] = (summary["count"] / summary["total"] * 100).round(2)

summary

   Country Political Bias positive/neutral/negative  count  total  percent
0   Canada         Center                  negative     16    149    10.74
1   Canada         Center                   neutral    122    149    81.88
2   Canada         Center                  positive     11    149     7.38
3   Canada           Left                  negative      8     76    10.53
4   Canada           Left                   neutral     54     76    71.05
5   Canada           Left                  positive     14     76    18.42
6   Canada          Right                  negative     46     75    61.33
7   Canada          Right                   neutral     26     75    34.67
8   Canada          Right                  positive      3     75     4.00
9       US         Center                  negative      3     60     5.00
10      US         Center                   neutral     53     60    88.33
11      US         Center                  positive      4     60     6.67
12      US           Left                  negative      3     70     4.29
13      US           Left                   neutral     62     70    88.57
14      US           Left                  positive      5     70     7.14
15      US          Right                  negative     17     70    24.29
16      US          Right                   neutral     50     70    71.43
17      US          Right                  positive      3     70     4.29

In [3]:
sentiment_col = "open coding/categories"
country_col = "Country"
bias_col = "positive/neutral/negative"  # changed column names depnding on analysis

df[sentiment_col] = df[sentiment_col].str.lower().str.strip()
df[bias_col] = df[bias_col].str.strip()


summary = (
    df.groupby([country_col, bias_col, sentiment_col])
    .size()
    .reset_index(name="count")
)


totals = (
    df.groupby([country_col, bias_col])
    .size()
    .reset_index(name="total")
)


summary = summary.merge(totals, on=[country_col, bias_col])


summary["percent"] = (summary["count"] / summary["total"] * 100).round(2)

summary

,Country,positive/neutral/negative,open coding/categories,count,total,percent
0,Canada,negative,2025 elections/campaigning/federal parties,7,70,10.00
1,Canada,negative,biography/opinion/criticism/personal details,50,70,71.43
2,Canada,negative,canada/us relations,1,70,1.43
3,Canada,negative,canadian domestic governance/economy/industry,12,70,17.14
4,Canada,neutral,2025 elections/campaigning/federal parties,42,202,20.79
5,Canada,neutral,biography/opinion/criticism/personal details,16,202,7.92
6,Canada,neutral,canada/us relations,25,202,12.38
7,Canada,neutral,canadian domestic governance/economy/industry,63,202,31.19
8,Canada,neutral,culture/social life/events/sports,16,202,7.92
9,Canada,neutral,international relations & diplomacy,40,202,19.80
10,Canada,positive,2025 elections/campaigning/federal parties,17,28,60.71
11,Canada,positive,biography/opinion/criticism/personal details,1,28,3.57
12,Canada,positive,canadian domestic governance/economy/industry,9,28,32.14
13,Canada,positive,international relations & diplomacy,1,28,3.57
14,US,negative,2025 elections/campaigning/federal parties,2,23,8.70
15,US,negative,biography/opinion/criticism/personal details,7,23,30.43
16,US,negative,canada/us relations,9,23,39.13
17,US,negative,culture/social life/events/sports,1,23,4.35
18,US,negative,international relations & diplomacy,4,23,17.39
19,US,neutral,2025 elections/campaigning/federal parties,35,165,21.21
20,US,neutral,biography/opinion/criticism/personal details,4,165,2.42
21,US,neutral,canada/us relations,91,165,55.15
22,US,neutral,canadian domestic governance/economy/industry,13,165,7.88
23,US,neutral,culture/social life/events/sports,3,165,1.82
24,US,neutral,international relations & diplomacy,19,165,11.52
25,US,positive,2025 elections/campaigning/federal parties,7,12,58.33
26,US,positive,biography/opinion/criticism/personal details,1,12,8.33
27,US,positive,canada/us relations,2,12,16.67
28,US,positive,international relations & diplomacy,2,12,16.67

In [13]:
category_col = "open coding/categories"
country_col = "Country"
bias_col = "Political Bias"
sentiment_col = "positive/neutral/negative"


df[category_col] = df[category_col].astype(str).str.strip()
df[country_col] = df[country_col].astype(str).str.strip()
df[bias_col] = df[bias_col].astype(str).str.strip()
df[sentiment_col] = df[sentiment_col].astype(str).str.lower().str.strip()

counts = (
    df.groupby([country_col, bias_col, category_col, sentiment_col])
      .size()
      .reset_index(name="count")
)


totals = (
    df.groupby([country_col, bias_col, category_col])
      .size()
      .reset_index(name="total")
)


merged = counts.merge(
    totals,
    on=[country_col, bias_col, category_col],
    how="left"
)


merged["percent"] = (merged["count"] / merged["total"] * 100).round(2)


pivot = merged.pivot_table(
    index=[country_col, bias_col, category_col],
    columns=sentiment_col,
    values="percent"
).fillna(0)


pivot = pivot[["positive", "neutral", "negative"]]

pivot

positive/neutral/negative                                             positive  \
Country Political Bias open coding/categories
Canada  Center         2025 Elections/Campaigning/Federal Parties        18.18
                       Biography/Opinion/Criticism/Personal Details       0.00
                       Canada/US Relations                                0.00
                       Canadian Domestic Governance/Economy/Industry     11.32
                       Culture/Social life/Events/Sports                  0.00
                       International Relations & Diplomacy                2.94
        Left           2025 Elections/Campaigning/Federal Parties        35.48
                       Biography/Opinion/Criticism/Personal Details       7.69
                       Canada/US Relations                                0.00
                       Canadian Domestic Governance/Economy/Industry      9.09
                       Culture/Social life/Events/Sports                  0.00
                       International Relations & Diplomacy                0.00
        Right          2025 Elections/Campaigning/Federal Parties        15.38
                       Biography/Opinion/Criticism/Personal Details       0.00
                       Canada/US Relations                                0.00
                       Canadian Domestic Governance/Economy/Industry     11.11
                       Culture/Social life/Events/Sports                  0.00
                       International Relations & Diplomacy                0.00
US      Center         2025 Elections/Campaigning/Federal Parties        25.00
                       Biography/Opinion/Criticism/Personal Details       0.00
                       Canada/US Relations                                0.00
                       Canadian Domestic Governance/Economy/Industry      0.00
                       International Relations & Diplomacy               16.67
        Left           2025 Elections/Campaigning/Federal Parties        15.00
                       Canada/US Relations                                3.57
                       Canadian Domestic Governance/Economy/Industry      0.00
                       Culture/Social life/Events/Sports                  0.00
                       International Relations & Diplomacy                7.69
        Right          2025 Elections/Campaigning/Federal Parties         8.33
                       Biography/Opinion/Criticism/Personal Details       9.09
                       Canada/US Relations                                2.56
                       Culture/Social life/Events/Sports                  0.00
                       International Relations & Diplomacy                0.00

positive/neutral/negative                                             neutral  \
Country Political Bias open coding/categories
Canada  Center         2025 Elections/Campaigning/Federal Parties       63.64
                       Biography/Opinion/Criticism/Personal Details     57.14
                       Canada/US Relations                              95.65
                       Canadian Domestic Governance/Economy/Industry    73.58
                       Culture/Social life/Events/Sports               100.00
                       International Relations & Diplomacy              97.06
        Left           2025 Elections/Campaigning/Federal Parties       61.29
                       Biography/Opinion/Criticism/Personal Details     61.54
                       Canada/US Relations                             100.00
                       Canadian Domestic Governance/Economy/Industry    77.27
                       Culture/Social life/Events/Sports               100.00
                       International Relations & Diplomacy             100.00
        Right          2025 Elections/Campaigning/Federal Parties       69.23
                       Biography/Opinion/Criticism/Personal Details      8.51
                       Canada/US Relations                             100.00
                       Canadian Domestic Governance/Economy/Industry    77.78
                       Culture/Social life/Events/Sports               100.00
                       International Relations & Diplomacy             100.00
US      Center         2025 Elections/Campaigning/Federal Parties       75.00
                       Biography/Opinion/Criticism/Personal Details      0.00
                       Canada/US Relations                              94.29
                       Canadian Domestic Governance/Economy/Industry   100.00
                       International Relations & Diplomacy              83.33
        Left           2025 Elections/Campaigning/Federal Parties       85.00
                       Canada/US Relations                              85.71
                       Canadian Domestic Governance/Economy/Industry   100.00
                       Culture/Social life/Events/Sports               100.00
                       International Relations & Diplomacy              92.31
        Right          2025 Elections/Campaigning/Federal Parties       75.00
                       Biography/Opinion/Criticism/Personal Details     36.36
                       Canada/US Relations                              87.18
                       Culture/Social life/Events/Sports                50.00
                       International Relations & Diplomacy              33.33

positive/neutral/negative                                             negative
Country Political Bias open coding/categories
Canada  Center         2025 Elections/Campaigning/Federal Parties        18.18
                       Biography/Opinion/Criticism/Personal Details      42.86
                       Canada/US Relations                                4.35
                       Canadian Domestic Governance/Economy/Industry     15.09
                       Culture/Social life/Events/Sports                  0.00
                       International Relations & Diplomacy                0.00
        Left           2025 Elections/Campaigning/Federal Parties         3.23
                       Biography/Opinion/Criticism/Personal Details      30.77
                       Canada/US Relations                                0.00
                       Canadian Domestic Governance/Economy/Industry     13.64
                       Culture/Social life/Events/Sports                  0.00
                       International Relations & Diplomacy                0.00
        Right          2025 Elections/Campaigning/Federal Parties        15.38
                       Biography/Opinion/Criticism/Personal Details      91.49
                       Canada/US Relations                                0.00
                       Canadian Domestic Governance/Economy/Industry     11.11
                       Culture/Social life/Events/Sports                  0.00
                       International Relations & Diplomacy                0.00
US      Center         2025 Elections/Campaigning/Federal Parties         0.00
                       Biography/Opinion/Criticism/Personal Details     100.00
                       Canada/US Relations                                5.71
                       Canadian Domestic Governance/Economy/Industry      0.00
                       International Relations & Diplomacy                0.00
        Left           2025 Elections/Campaigning/Federal Parties         0.00
                       Canada/US Relations                               10.71
                       Canadian Domestic Governance/Economy/Industry      0.00
                       Culture/Social life/Events/Sports                  0.00
                       International Relations & Diplomacy                0.00
        Right          2025 Elections/Campaigning/Federal Parties        16.67
                       Biography/Opinion/Criticism/Personal Details      54.55
                       Canada/US Relations                               10.26
                       Culture/Social life/Events/Sports                 50.00
                       International Relations & Diplomacy               66.67

In [14]:
sentiment_col = "open coding/categories"
country_col = "Country"
bias_col = "positive/neutral/negative"

df[sentiment_col] = df[sentiment_col].str.lower().str.strip()
df[bias_col] = df[bias_col].str.strip()


summary = (
    df.groupby([country_col, bias_col, sentiment_col])
    .size()
    .reset_index(name="count")
)


totals = (
    df.groupby([country_col, bias_col])
    .size()
    .reset_index(name="total")
)


summary = summary.merge(totals, on=[country_col, bias_col])


summary["percent"] = (summary["count"] / summary["total"] * 100).round(2)

summary

,Country,positive/neutral/negative,open coding/categories,count,total,percent
0,Canada,negative,2025 elections/campaigning/federal parties,7,70,10.00
1,Canada,negative,biography/opinion/criticism/personal details,50,70,71.43
2,Canada,negative,canada/us relations,1,70,1.43
3,Canada,negative,canadian domestic governance/economy/industry,12,70,17.14
4,Canada,neutral,2025 elections/campaigning/federal parties,42,202,20.79
5,Canada,neutral,biography/opinion/criticism/personal details,16,202,7.92
6,Canada,neutral,canada/us relations,25,202,12.38
7,Canada,neutral,canadian domestic governance/economy/industry,63,202,31.19
8,Canada,neutral,culture/social life/events/sports,16,202,7.92
9,Canada,neutral,international relations & diplomacy,40,202,19.80
10,Canada,positive,2025 elections/campaigning/federal parties,17,28,60.71
11,Canada,positive,biography/opinion/criticism/personal details,1,28,3.57
12,Canada,positive,canadian domestic governance/economy/industry,9,28,32.14
13,Canada,positive,international relations & diplomacy,1,28,3.57
14,US,negative,2025 elections/campaigning/federal parties,2,23,8.70
15,US,negative,biography/opinion/criticism/personal details,7,23,30.43
16,US,negative,canada/us relations,9,23,39.13
17,US,negative,culture/social life/events/sports,1,23,4.35
18,US,negative,international relations & diplomacy,4,23,17.39
19,US,neutral,2025 elections/campaigning/federal parties,35,165,21.21
20,US,neutral,biography/opinion/criticism/personal details,4,165,2.42
21,US,neutral,canada/us relations,91,165,55.15
22,US,neutral,canadian domestic governance/economy/industry,13,165,7.88
23,US,neutral,culture/social life/events/sports,3,165,1.82
24,US,neutral,international relations & diplomacy,19,165,11.52
25,US,positive,2025 elections/campaigning/federal parties,7,12,58.33
26,US,positive,biography/opinion/criticism/personal details,1,12,8.33
27,US,positive,canada/us relations,2,12,16.67
28,US,positive,international relations & diplomacy,2,12,16.67